name: educate_me
description: Mathematics Educate Me Official App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #stacked service
  stacked:
  stacked_services:
  stacked_themes:
  stacked_generator:
  #injection
  get:
  rxdart:
  provider:
  #network
  dio: 4.0.0

  #firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_remote_config:
  #auth
  google_sign_in:
  the_apple_sign_in: ^1.1.1
  #utils
  intl:
  google_fonts:
  shimmer:
  path_provider:
  cached_network_image:
  url_launcher:
  responsive_builder:
  auto_size_text: ^3.0.0-nullsafety.0
  animations:
  iconsax:
  animated_text_kit:
  styled_widget:
  shared_preferences:
  logger:
  pretty_dio_logger:
  image_picker:
  image_cropper:
  dotted_border:
  lottie:
  flutter_svg: ^1.0.3
  grouped_list:
  flutter_slidable: ^1.3.0
  badges:
  flutter_screenutil:
  uuid:
  #pickers
  flutter_picker:
  #payments
  flutter_inapp_purchase: ^5.1.2
  #drawing
  flutter_drawing_board:
  draw_your_image:
  painter:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

