// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzO_MlOmFycyCyL1qMzbtwBr_PEb2OlLg',
    appId: '1:763894577183:web:d9a4fcd29f09bff4d77d2a',
    messagingSenderId: '763894577183',
    projectId: 'math-educate-me',
    authDomain: 'math-educate-me.firebaseapp.com',
    storageBucket: 'math-educate-me.appspot.com',
    measurementId: 'G-2PJF8WNXNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAgIL91OPvLya2XLVDX66oVFwK3KBhzqs',
    appId: '1:763894577183:android:090afc0884f62ad6d77d2a',
    messagingSenderId: '763894577183',
    projectId: 'math-educate-me',
    storageBucket: 'math-educate-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA03lMlpN-27Omfz3UhD0BXt-PI7HGLc0',
    appId: '1:763894577183:ios:a314ffd758c12e0cd77d2a',
    messagingSenderId: '763894577183',
    projectId: 'math-educate-me',
    storageBucket: 'math-educate-me.appspot.com',
    iosClientId: '763894577183-61gpm0nl45lhpkcjknmt92he23nnjq05.apps.googleusercontent.com',
    iosBundleId: 'com.educateme.educateMe',
  );
}
